from .frame_corelation_table import CorrelationFrame
from .frame_history_data import HistoryDataFrame
from .frame_currencies_data import CryptocurrencyDataFrame
from .frame_neuronal import NeuronalesNetzFrame
from .frame_market_data import ExchangeDataFrame
from .frame_symbol_data import SymbolDataFrame
from .frame_corelation_graph import CorrelationGraphFrame
from .frame_import_history import ImportHistoryFrame
from .frame_autocorrelation_graph import AutocorrelationGraphFrame
from .frame_ohlc_graph import OhlcGraphFrame
from .frame_garch_analyse_mean import GARCHFrameChanging
from .frame_garch_analyse import GARCHFrame
from .frame_linear_regression_graph import LinearRegressionGraphFrame
from .main_form import MainForm

